name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Sync Version From JOSE
    types:
      - completed
  release:
    types:
      - published
      - released

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      # Setup .npmrc file to publish to npm
      - name: Set up environment
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      - name: Build
        run: npm i && npm run compile

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
