name: CD

on:
  release:
    types:
      - published
      - released

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      # Setup .npmrc file to publish to npm
      - name: Set up environment
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      - name: Build
        run: npm i && npm run compile

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
