name: Publish to NPM

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Sync Version From JOSE
    types:
      - completed
  release:
    types:
      - published
      - released

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      # Setup .npmrc file to publish to npm
      - name: Set up environment
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      - name: Check version
        id: should_process
        run: |
          NPM_VERSION=$(npm view ts-jose version)
          PACKAGE_VERSION=$(npm version | grep "^[ ']*ts-jose" | tr -dc '0-9.')
          [[ $NPM_VERSION == $PACKAGE_VERSION ]] && VALUE="false" || VALUE="true"
          echo "::set-output name=value::$VALUE"

      - name: Build
        if: ${{ steps.should_process.outputs.value == 'true' }}
        run: npm i && npm run compile

      - name: Publish
        if: ${{ steps.should_process.outputs.value == 'true' }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
