name: Sync Version From JOSE

on:
  schedule:
    # sync every day
    - cron: "30 0 * * *"

  workflow_dispatch:
    # Enable manual run
    inputs:
      version:
        description: "JOSE version"
        required: true
        default: "0.0.0"

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.output.outputs.value }}
    steps:
      - name: Check tag exist
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://github.com/panva/jose/releases/tag/v${{ github.event.inputs.version }})
          if [[ $STATUS = '404' ]]; then; exit 1; fi
      - name: Get JOSE latest tag
        if: ${{ github.event_name == 'schedule' }}
        id: jose-tag
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: panva
          repo: jose
      - name: Trim tag
        if: ${{ github.event_name == 'schedule' }}
        id: jose-version
        run: |
          v=$(echo ${{ steps.jose-tag.outputs.release }} | cut -c 2-)
          echo "::set-output name=v::$v"
      - name: Determine version
        uses: haya14busa/action-cond@v1
        id: output
        with:
          cond: ${{ github.event_name == 'workflow_dispatch' }}
          if_true: ${{ github.event.inputs.version }}
          if_false: ${{ steps.jose-version.outputs.v }}

  check:
    runs-on: ubuntu-latest
    needs: version
    outputs:
      version: ${{ steps.output.outputs.value }}
    steps:
      - uses: actions/checkout@v2

      - name: Get package.json version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Check version
        uses: actions/github-script@v4
        id: check-result
        with:
          script: |
            const target = '${{ needs.version.outputs.version }}'.split('.').map(e => Number(e));
            const source = '${{ steps.package-version.outputs.current-version }}'.split('.').map(e => Number(e));
            if (target.length != source.length || target.some(isNaN) || source.some(isNaN)) {
              return false;
            }
            if (target[0] == source[0]) {
              if (target[1] == source[1]) {
                return target[2] > source[2];
              }
              return target[1] > source[1];
            }
            return target[2] > source[2];
      - name: Determine version
        uses: haya14busa/action-cond@v1
        id: output
        with:
          cond: ${{ steps.check-result.outputs.result == 'true' }}
          if_true: ${{ needs.version.outputs.version }}
          if_false: ""

  sync:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.version != '' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: Bump package.json version
        run: npm version --no-commit-hooks ${{ needs.check.outputs.version }}

      - name: Update JOSE version
        run: |
          npm i jose@${{ needs.check.outputs.version }}
          npm i
          npm test

      - name: Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit . -m "Bump version to ${{ needs.check.outputs.version }}"

      - name: Push commit and tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          tags: true

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check.outputs.version }}
          release_name: v${{ needs.check.outputs.version }}
          body: "This is auto-generate from GitHub Actions\nSource diff can see [here](https://github.com/panva/jose/releases/tag/v${{ needs.check.outputs.version }})"
