name: "Test and lint"

on:
  workflow_dispatch:

  pull_request:

  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".github/**"

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x,20.x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i # clean install

      - name: Check format
        if: ${{ startsWith(matrix.node-version, '12') }}
        run: npm run lint

      - name: Unit test
        run: npm run test

  coverage: # build coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Coverage
        run: npm run test:cov && npx codecov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage
